patches/riscvnommu: fix PTRACE_GETFDPIC numbering
Linux-6.4 kernel introduced some new PTRACE definitions for RISC-V.
The patched in support for ELF format no-MMU binaries now errors out
on a numbering clash at compile time:

      CC      kernel/ptrace.o
    kernel/ptrace.c: In function ‘ptrace_request’:
    kernel/ptrace.c:1214:9: error: duplicate case value
     1214 |         case PTRACE_SYSEMU:
          |         ^~~~
    kernel/ptrace.c:1184:9: note: previously used here
     1184 |         case PTRACE_GETFDPIC: {
          |         ^~~~

Renumber the PTRACE_GETFDPIC definition so it is good again.

Signed-off-by: Greg Ungerer <gerg@kernel.org>